#!/usr/bin/env bash
# mint-agent-secret-ids.sh — Phase D (OPS-464)
# Operator session bootstrap: mint per-role AppRole secret_ids for agent sessions.
#
# Replaces the root-VAULT_TOKEN injection into /tmp/sess.env.
# After this script runs, each agent can call:
#   agent-vault-auth.sh <role>
# using only AGENT_ROLE_ID + AGENT_SECRET_ID (no root token in agent env).
#
# Usage:
#   bash scripts/mint-agent-secret-ids.sh [role [role ...]]
#
# If no roles are specified, mints for all four: worker planner judge scribe.
# If specific roles are given, mints only for those.
#
# Output:
#   Writes to /tmp/sess.env (or $SESS_ENV_FILE if set).
#   Format: shell-compatible variable assignments, one block per role.
#   The file is mode 0600 (contains credentials).
#
# Prerequisites:
#   - VAULT_TOKEN in env (operator root or admin token — stays in OPERATOR session,
#     NOT injected into agent env)
#   - VAULT_ADDR in env (defaults to https://vault.208.haist.farm)
#   - vault CLI in PATH or ~/.local/bin/vault
#   - The agent-<role>-bootstrap AppRoles and KV role_id entries must exist
#     (run vault-approle-agent-bootstrap.yml playbook first)
#
# Security model:
#   - Operator holds root VAULT_TOKEN (stays in operator session only).
#   - This script mints 1-hour, single-use secret_ids.
#   - /tmp/sess.env gets AGENT_ROLE_ID + AGENT_SECRET_ID per role.
#   - Agent bootstraps via AppRole (no root token ever in agent env).
#   - VAULT_TOKEN is NOT written to /tmp/sess.env.
#
# Tracking: OPS-464 Phase D

set -euo pipefail

VAULT_ADDR="${VAULT_ADDR:-https://vault.208.haist.farm}"
export VAULT_ADDR

SESS_ENV_FILE="${SESS_ENV_FILE:-/tmp/sess.env}"

# ── Helpers ──────────────────────────────────────────────────────────────────

log() { echo "[mint-agent-secret-ids] $*" >&2; }
err() { echo "[mint-agent-secret-ids] ERROR: $*" >&2; }

# ── Vault CLI path ────────────────────────────────────────────────────────────

if ! command -v vault &>/dev/null; then
    if [[ -x "${HOME}/.local/bin/vault" ]]; then
        export PATH="${HOME}/.local/bin:${PATH}"
    else
        err "vault CLI not found. Install vault or add ~/.local/bin/vault."
        exit 1
    fi
fi

# ── Pre-flight ────────────────────────────────────────────────────────────────

if [[ -z "${VAULT_TOKEN:-}" ]]; then
    err "VAULT_TOKEN is not set. This script requires an operator (root or admin) Vault token."
    err "The token stays in your session — it will NOT be written to ${SESS_ENV_FILE}."
    exit 1
fi

log "VAULT_ADDR: ${VAULT_ADDR}"
log "Output file: ${SESS_ENV_FILE}"

# ── Role selection ────────────────────────────────────────────────────────────

ALL_ROLES=(worker planner judge scribe)

if [[ $# -eq 0 ]]; then
    ROLES=("${ALL_ROLES[@]}")
else
    ROLES=("$@")
    for r in "${ROLES[@]}"; do
        case "${r}" in
            worker|planner|judge|scribe) ;;
            *)
                err "Unknown role: '${r}'. Valid roles: worker planner judge scribe"
                exit 1
                ;;
        esac
    done
fi

log "Minting secret_ids for roles: ${ROLES[*]}"

# ── Write output file header (mode 0600) ─────────────────────────────────────

# Ensure directory exists and write with restricted permissions
touch "${SESS_ENV_FILE}" && chmod 0600 "${SESS_ENV_FILE}"

cat > "${SESS_ENV_FILE}" <<HEADER
# Agent bootstrap env — generated by mint-agent-secret-ids.sh (OPS-464 Phase D)
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Valid for: 1 hour from generation time (secret_id_ttl=1h, num_uses=1)
# DO NOT share this file — it contains one-use authentication credentials.
# Operator root VAULT_TOKEN is NOT in this file by design.

HEADER

# ── Mint secret_ids per role ──────────────────────────────────────────────────

for ROLE in "${ROLES[@]}"; do
    log "Processing role: ${ROLE}"

    APPROLE_ROLE="agent-${ROLE}-bootstrap"
    ROLE_ID_KV_PATH="secret/vault/agent-${ROLE}-bootstrap-role-id"

    # Read stable role_id from Vault KV (written by Ansible playbook)
    log "  Reading role_id from ${ROLE_ID_KV_PATH}..."
    ROLE_ID=$(vault kv get -field=role_id "${ROLE_ID_KV_PATH}" 2>/dev/null) || {
        err "  Failed to read role_id from ${ROLE_ID_KV_PATH}."
        err "  Has the vault-approle-agent-bootstrap.yml playbook been run?"
        exit 1
    }

    if [[ -z "${ROLE_ID}" ]]; then
        err "  role_id is empty for role=${ROLE}. Re-run the Ansible playbook."
        exit 1
    fi

    # Mint single-use secret_id (operator action — uses root VAULT_TOKEN)
    log "  Minting single-use secret_id (TTL=1h, num_uses=1)..."
    SECRET_ID=$(vault write -field=secret_id \
        "auth/approle/role/${APPROLE_ROLE}/secret-id" \
        2>/dev/null) || {
        err "  Failed to mint secret_id for AppRole ${APPROLE_ROLE}."
        err "  Verify the AppRole exists: vault read auth/approle/role/${APPROLE_ROLE}"
        exit 1
    }

    if [[ -z "${SECRET_ID}" ]]; then
        err "  Vault returned empty secret_id for ${APPROLE_ROLE}."
        exit 1
    fi

    # Write block to sess.env
    # Variable names are role-prefixed to support multi-agent sessions
    ROLE_UPPER="${ROLE^^}"
    cat >> "${SESS_ENV_FILE}" <<ROLE_BLOCK
# Role: ${ROLE}
export AGENT_${ROLE_UPPER}_ROLE_ID="${ROLE_ID}"
export AGENT_${ROLE_UPPER}_SECRET_ID="${SECRET_ID}"

ROLE_BLOCK

    # Clear secret from shell variable (best-effort)
    SECRET_ID=""
    unset SECRET_ID

    log "  Done — secret_id minted for role=${ROLE} (AGENT_${ROLE_UPPER}_ROLE_ID + AGENT_${ROLE_UPPER}_SECRET_ID written to ${SESS_ENV_FILE})"
done

log ""
log "Complete. To use in an agent session:"
log "  source ${SESS_ENV_FILE}"
log ""
log "Then start the agent. It will call:"
log "  agent-vault-auth.sh <role>"
log "which reads AGENT_<ROLE>_ROLE_ID + AGENT_<ROLE>_SECRET_ID from env."
log ""
log "NOTE: Each secret_id is single-use and expires in 1 hour."
log "Re-run this script at session start to mint fresh credentials."
