[control_node]
iac-control ansible_connection=local

[git_servers]
gitlab-server ansible_host=192.168.12.68 ansible_user=koiakoia

[iac_control]
iac-control ansible_host=localhost ansible_connection=local

[config_servers]
config-server ansible_host=10.0.0.2 ansible_user=koiakoia
