---
- name: Restart haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
    enabled: true

- name: Restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
    enabled: true

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true

- name: Restart keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
    enabled: true

- name: Daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
